import 'package:quotes_application/headers.dart';

List<TextStyle> quoteFontFamily = [
  GoogleFonts.abel(),
  GoogleFonts.roboto(),
  GoogleFonts.dancingScript(),
  GoogleFonts.bitter(),
  GoogleFonts.anton(),
  GoogleFonts.yatraOne(),
  GoogleFonts.pacifico(),
  GoogleFonts.fjallaOne(),
  GoogleFonts.shadowsIntoLight(),
  GoogleFonts.indieFlower(),
  GoogleFonts.zillaSlab(),
  GoogleFonts.satisfy(),
  GoogleFonts.permanentMarker(),
  GoogleFonts.amaticSc(),
  GoogleFonts.cinzel(),
  GoogleFonts.sairaCondensed(),
  GoogleFonts.kalam(),
  GoogleFonts.courgette(),
  GoogleFonts.righteous(),
  GoogleFonts.tinos(),
  GoogleFonts.lobster(),
  GoogleFonts.changa(),
  GoogleFonts.greatVibes(),
  GoogleFonts.zeyada(),
  GoogleFonts.aladin(),
  GoogleFonts.kaushanScript(),
  GoogleFonts.pathwayGothicOne(),
  GoogleFonts.sacramento()
];
